// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { envServer } from "@/shared/config/env/env.server";
import "dotenv/config";

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envServer.DATABASE_URL,
  },
});
